- frontend/src/components/account/Register.jsx
Reverts HopHacks/hophacks-flask#100
> Revert "MLH stuff"

- api/src/app.py
- api/src/discord.py
- api/src/slack.py
Add a config to check whether a webhook for the API is provided.
> Slack / Discord API Optional

- frontend/src/components/Footer.jsx
- frontend/src/components/Home.jsx
- frontend/src/components/LoginDialog.jsx
- frontend/src/components/Nav.jsx
- frontend/src/components/home/Faq.jsx
- frontend/src/stylesheets/home.css
changed all font on homepage to inter, updated mlh badge to 2023 and made it appear on all pages
> Julia josephine navbar

- frontend/src/components/account/Profile.jsx
- frontend/src/components/account/Register.jsx
Adds a required age field to registration.
> Add age field

- frontend/src/components/home/Team.jsx
team page is centered, tabs are horizontally scrollable
> Julia josephine team

- api/src/registrations.py
- frontend/src/components/admin/Admin.jsx
1. add but comment out the configured rsvp button for users
2. add send all rsvp info email features to all current rsvped users in the admin page
> Rsvp email

- frontend/src/components/home/About.jsx
- frontend/src/components/home/AboutTransition.jsx
Reverts HopHacks/hophacks-flask#227
> Revert "resize the about page"

- frontend/src/components/Home.jsx
- frontend/src/components/home/Cover.jsx
i made the mobile cover page look like how it was before, not sure if that is what you want but it's an option! also cleaned up home.jsx, checking window.innerWidth <= 650 is in cover.jsx now
> made mobile cover page look like how it was before

- frontend/src/components/Home.jsx
Make footer of website full length
After
Before
> Make footer full length

- api/src/accounts.py
- api/src/app.py
- api/src/registrations.py
Reverts HopHacks/hophacks-flask#267
Seeing if this fixes backend issues
> Revert "Email Service"

- frontend/src/components/home/Team.jsx
- Move Kelly to `Alumni` tab of team page
- Add Lyn to `Directors` tab of team page
- Change Joanne's photo in AWS S3
> Faculty edits on team page

- frontend/src/components/Home.jsx
- frontend/src/components/home/AboutSeparation.jsx
- frontend/src/components/home/Prizes.jsx
- frontend/src/components/home/Sponsors.jsx
- frontend/src/stylesheets/home.css
Prize section doesn't seem to have a Figma. Created a basic implementation.
Added four current sponsors.
> Prize and Sponsor Sections

- frontend/src/components/admin/Admin.jsx
> Admin page UI styling

- api/src/accounts.py
- api/src/admin.py
- api/src/resumes.py
- api/src/vaccination.py
- frontend/src/components/account/Profile.jsx
- frontend/src/components/register/signup/SignUp.jsx
- frontend/src/components/register/signup/SignUpProfile.jsx
1. added the 3 new questions to registration and profile questions
2. re added vaccination file to profile page
3. fixed resume and vaccination file page retrieval(hopefully)
Note: Most of these changes are hard to test locally so preferably let me know when this is getting merged so I can make quick fixes.
> Update profile questions

- frontend/src/components/home/Sponsors.jsx
- frontend/src/stylesheets/home.css
Had to add background for Google Cloud logo because the word "Google Cloud" is extremely hard to see on transparent background
Can't find good logos for JHU CS and ME department.
> Add more sponsors

- frontend/src/components/register/ResetPassword.jsx
Uncommented reset password function and called it on click
Need to test once deployed?
> Fix reset password

- frontend/src/components/home/Prizes.jsx
- frontend/src/stylesheets/home.css
> update prizes section

- api/src/registrations.py
> reenable rsvps

- frontend/src/components/home/Sponsors.jsx
> update bloomberg logo

- frontend/src/components/admin/Admin.jsx
Added "accepted" status filter to admin page
Search filters no longer reset on click
> Admin page chanages

- frontend/src/components/home/Prizes.jsx
added second row of prizes based on new tracks.
> added second row of prizes

- api/src/assign.py
added judge tool modifications
> Judgetool changes

- frontend/package-lock.json
- frontend/src/components/App.jsx
- frontend/src/components/Nav.jsx
- frontend/src/components/Recruiting.jsx
- frontend/src/components/Team.jsx
- frontend/src/stylesheets/recruit.css
- frontend/yarn.lock
Changed homepage to recruit. 
Updated the layout of recruit page. 
Disabled all routes other than recruit and team.
> Org application

- frontend/src/components/account/Profile.jsx
changed equality from == to ===
> bug fix in cross year accounts

- api/src/resumes.py
- frontend/src/components/account/Profile.jsx
> Deployment test

- api/src/resumes.py
fixed bug where resume upload needed array of users instead of just one
> fixed bug in resume upload, for cross accounts

- api/src/resumes.py
fixed bug with wrong id being updated
> Cross year account

- api/src/admin.py
life is no longer pain?
- updated admin page to only show current event registrations.
> Cross year account admin

- frontend/src/components/account/ProfileReturningUser.jsx
- frontend/src/components/home/Team.jsx
- frontend/src/components/user_auth/signup/SignUpChecks.jsx
added photo release pieces
updated team page
> 2024 mlh requests

- frontend/src/components/home/Sponsors.jsx
> Added sponsors

- api/src/templates/email_reset.html
- api/src/templates/email_template.html
- api/src/templates/old template/email_acceptance.html
- api/src/templates/old template/email_apply_confirm.html
- api/src/templates/old template/email_confirmation.html
- api/src/templates/old template/email_reset.html
- api/src/templates/old template/email_template.html
- api/src/templates/rsvpinfo.html
> updated email template dates and discord links

- api/src/templates/old template/email_reset.html
- api/src/templates/rsvpinfo.html
> changed email templates

- api/src/templates/rsvpinfo.html
added tentatively to check in info
added dietary restrictions form
> Updated RSVP Email

- frontend/src/components/admin/Admin.jsx
fixed filtering bug where admin page would show filtering based on previous years as well
> Sponsors2024 final

- api/src/templates/rsvpinfo.html
> removed spacing issue

- api/src/assign.py
- frontend/src/components/Footer.jsx
- frontend/src/components/Nav.jsx
- frontend/src/components/home/Schedule.jsx
- frontend/src/components/home/Sponsors.jsx
-added logo to header + footer, 
-added palantir, 
-updated tentative schedule according to run of show
> added logo to header + footer, added palantir, updated schedule

- frontend/src/components/home/Sponsors.jsx
> Sponsors updated logo

- api/src/assign.py
updated judge tool to assign sponsors using a separate column
> Judge tool update

- api/src/admin.py
- api/src/registrations.py
updated admin page to sort based on rsvp time if it exists
> upated rsvp

- api/src/admin.py
hopefully am a little less dumb now
(fixed registrations object to still return as an array)
> Rsvp ordering

- frontend/src/components/home/Schedule.jsx
Updated schedule to final schedule for Fall 2024
> Updated schedule

- frontend/src/components/home/Schedule.jsx
updated some locations and removed JHU it duplicate
> Schedule Update

- frontend/src/components/admin/Admin.jsx
added checked in resume button
> added download button for checked in resumes

- api/src/assign.py
- frontend/src/components/admin/Admin.jsx
- fixed issue if track column in judge tool is empty
- added age to admin page to look at during acceptances
> fixed judge tool and added age to admin page

- frontend/public/home.js
- frontend/src/components/home/Cover.jsx
- frontend/src/stylesheets/cover.css
Implemented the front page.
fix names of sections to temporarily block the unnecessary sections, also moved the design components to cover.css
> Leon's Cover Page Design Implementation

- .github/workflows/prettier.yml
> Update prettier.yml with downgraded version

- api/src/auth.py
- api/src/templates/email_acceptance.html
- Reformatted the acceptance email to match 2025 theme
- Fixed Bug where a new Fall 2025 registration was being created because I forgot to change one "Fall 2024" to "Fall 2025" in an if statement (in the future we might want to make it so we change the event in one place and then it changes it everywhere)
> Email Update and Registration Bug Fix

- .github/workflows/deploy.yml
TODO need to add secrets still!
> EC2 deployment workflow

- api/src/admin.py
- frontend/src/components/admin/Admin.jsx
- Can now see the date the hacker applied on the panel
- Can sort by the date too now
> Admin Page Update

- api/src/accounts.py
Bug where, duplicate Fall 2025 registration events were being created for returning hackers
> Fixed duplication bug

- frontend/src/components/admin/Admin.jsx
- can now see age in the admin panel
> Age Change to Admin Panel

- frontend/src/components/Home.jsx
- frontend/src/components/home/Schedule.jsx
Adding styling fixes to schedule
Fun elements like emojis
> Schedule update2025

- frontend/src/components/account/ProfileReturningUser.jsx
- frontend/src/components/judgetool/Upload.jsx
Fix ui changes in /upload route for judge tool
> Waitlist fix
